"""set of Widgets to help configure Elk Layout Options
https://www.eclipse.org/elk/reference/options.html
"""

# Copyright (c) 2024 ipyelk contributors.
# Distributed under the terms of the Modified BSD License.

from .edge_options import (
    Direction,
    EadesRepulsion,
    EdgeCenterLabelPlacementStrategy,
    EdgeEdgeLayerSpacing,
    EdgeLabelPlacement,
    EdgeLabelSideSelection,
    EdgeLabelSpacing,
    EdgeNodeLayerSpacing,
    EdgeNodeSpacing,
    EdgeRouting,
    EdgeSpacing,
    EdgeThickness,
    EdgeType,
    FeedbackEdges,
    MergeEdges,
    MergeHierarchyCrossingEdges,
)
from .layout import ELKRectanglePacking, LayoutAlgorithm
from .node_options import (
    ActivateInsideSelfLoops,
    AspectRatio,
    ConsiderModelOrder,
    ContentAlignment,
    ExpandNodes,
    HierarchyHandling,
    NodeLabelPlacement,
    NodeSizeConstraints,
    NodeSizeMinimum,
    NodeSizeOptions,
    Padding,
)
from .port_options import (
    AdditionalPortSpace,
    PortAnchorOffset,
    PortBorderOffset,
    PortConstraints,
    PortIndex,
    PortLabelPlacement,
    PortSide,
    TreatPortLabelsAsGroup,
)
from .selection_widgets import LayoutOptionWidget, OptionsWidget, SpacingOptionWidget
from .spacing_options import (
    CommentCommentSpacing,
    CommentNodeSpacing,
    ComponentsSpacing,
    LabelNodeSpacing,
    LabelSpacing,
    NodeSpacing,
    SeparateConnectedComponents,
)
from .wrapping_options import (
    AdditionalWrappedEdgesSpacing,
    CorrectionFactorForWrapping,
    GraphWrappingStrategy,
)

__all__ = [
    "ActivateInsideSelfLoops",
    "AdditionalPortSpace",
    "AdditionalWrappedEdgesSpacing",
    "AspectRatio",
    "CommentCommentSpacing",
    "CommentNodeSpacing",
    "ComponentsSpacing",
    "ConsiderModelOrder",
    "ContentAlignment",
    "CorrectionFactorForWrapping",
    "Direction",
    "EadesRepulsion",
    "EdgeCenterLabelPlacementStrategy",
    "EdgeEdgeLayerSpacing",
    "EdgeLabelPlacement",
    "EdgeLabelSideSelection",
    "EdgeLabelSpacing",
    "EdgeNodeLayerSpacing",
    "EdgeNodeSpacing",
    "EdgeRouting",
    "EdgeSpacing",
    "EdgeThickness",
    "EdgeType",
    "ELKRectanglePacking",
    "ExpandNodes",
    "FeedbackEdges",
    "GraphWrappingStrategy",
    "HierarchyHandling",
    "LabelNodeSpacing",
    "LabelSpacing",
    "LayoutAlgorithm",
    "LayoutOptionWidget",
    "MergeEdges",
    "MergeHierarchyCrossingEdges",
    "NodeLabelPlacement",
    "NodeSizeConstraints",
    "NodeSizeMinimum",
    "NodeSizeOptions",
    "NodeSpacing",
    "OptionsWidget",
    "Padding",
    "PortAnchorOffset",
    "PortBorderOffset",
    "PortConstraints",
    "PortIndex",
    "PortLabelPlacement",
    "PortSide",
    "SeparateConnectedComponents",
    "SpacingOptionWidget",
    "TreatPortLabelsAsGroup",
]
