name: test

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - anaconda-project =0.8.4
  - conda =4.9
  - doit ==0.32
  - mamba =0.7
  - pip
  - python >=3.7,<3.8
  - twine
  - wheel
