version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-latest
  jobs:
    pre_build:
      - pixi install --environment=build
      - pixi install --environment=lite
      - pixi install --environment=docs
      - pixi run setup-js
      - pixi run build
      - pixi run dist
      - pixi run docs-lite

conda:
  environment: docs/rtd.yml

sphinx:
  builder: html
  configuration: docs/conf.py
