"$schema" = "https://pixi.sh/v0.32.1/schema/manifest/schema.json"

# tasks ################################################################################
[tasks]
fix = {depends-on = ["fix-taplo", "fix-ruff-format", "fix-ruff-check"]}
lint = {depends-on = ["lint-ruff-format", "lint-ruff-check"]}
dev = {depends-on = ["fix", "lint"]}

# linting ##############################################################################
[feature.tasks-lint.tasks.fix-taplo]
description = "consistently format TOML files"
cmd = """taplo fmt
  *.toml
  --option=array_auto_collapse=true
  --option=compact_inline_tables=true
  --option=column_width=88"""
inputs = ["*.toml"]

[feature.tasks-lint.tasks.lint-ruff-format]
cmd = "ruff format --check"
inputs = ["{scripts,src,tests,docs,atest,examples}/**/*.{py,ipynb}", "pyproject.toml"]

[feature.tasks-lint.tasks.lint-ruff-check]
cmd = "ruff check"
inputs = ["{scripts,src,tests,docs,atest,examples}/**/*.{py,ipynb}", "pyproject.toml"]

[feature.tasks-lint.tasks.fix-ruff-format]
cmd = "ruff format"
inputs = ["{scripts,src,tests,docs,atest,examples}/**/*.{py,ipynb}", "pyproject.toml"]

[feature.tasks-lint.tasks.fix-ruff-check]
cmd = "ruff check --fix-only"
depends-on = ["fix-ruff-format"]
inputs = ["{scripts,src,tests,docs,atest,examples}/**/*.{py,ipynb}", "pyproject.toml"]

# dependencies #########################################################################
[feature.deps-lint.dependencies]
taplo = "*"
ruff = "*"

# environments #########################################################################
[environments]
lint = {features = ["deps-lint", "tasks-lint"]}

# meta #################################################################################
[project]
name = "ipyelk"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
