#!/usr/bin/env python3
""" a windows-friendly, binder-compatible script to get a development environment
"""

import platform
import shutil
import sys
from pathlib import Path
from subprocess import check_call

from jupyterlab_server.process import which

NPM = which("npm")
JLPM = which("jlpm")

LABEXTENSIONS = [".", "@jupyter-widgets/jupyterlab-manager"]

HERE = Path.cwd()
DIST = HERE / "dist"

DIST.exists() and shutil.rmtree(DIST)


def _(*args, **kwargs):
    if "cwd" in kwargs:
        kwargs["cwd"] = str(kwargs["cwd"])
    str_args = [str(a) for a in args]
    print(f"\n>>>\t{' '.join(str_args)}\n")
    check_call(str_args, **kwargs)


# preflight existing extensions
_("jupyter", "labextension", "list")
# avoid weird caching issues
_(JLPM, "cache", "clean")
# perform all the node stuff
_(JLPM, "bootstrap")
# build python packages
_(sys.executable, "setup.py", "bdist_wheel", "sdist")
# build labextension package
_(NPM, "pack", "..", cwd=DIST)
# install local python dev
_(sys.executable, "-m", "pip", "install", "-e", ".", "--no-deps")
# install labextensions
# NOTE: on binder, this seems to be breaking right now, but installing
#       the tgz works fine
_("jupyter", "labextension", "install", "--no-build", "--debug", *LABEXTENSIONS)
# do a production build of lab
_("jupyter", "lab", "build", "--debug", "--dev-build=False", "--minimize=True")
# list the extensions
_("jupyter", "labextension", "list")

print(">>> OK")
